services:
  
  actix-db:
    container_name: actixdb
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "-A scram-sha-256"
    volumes:
      - ./src/main/storage/migrations:/docker-entrypoint-initdb.d/
      - ./certs:/var/lib/postgresql/certs/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 10s
    networks:
      - dev_nk
    ports:
      - "5433:5432"
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
               -c ssl_key_file=/var/lib/postgresql/certs/server.key
               -c ssl_ca_file=/var/lib/postgresql/certs/root.crt

  actix-app:
    container_name: actix-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      actix-db:
        condition: service_healthy
    networks:
      - dev_nk
    ports:
      - "8080:8080"

networks:
  dev_nk:
    driver: bridge